[book]
authors = ["Hollow Man"]
language = "en"
multilingual = false
src = "src"
title = "An Example"

[output.html]

[output.html.print]
enable = true

[output.pdf]
# # For Windows only
# command = 'python ../../mdbook-pdf'
web-driver-path = ""
web-binary-path = ""
# https://w3c.github.io/webdriver/#print-page
orientation = "portrait"
scale = 1
background = true
page = "{}"
page-width = 21
page-height = 29.7
margin = "{}"
margin-top = 1
margin-bottom = 1
margin-left = 1
margin-right = 1
shrink-to-fit = true
page-ranges = "[]"
